import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheckCircle } from '@fortawesome/free-solid-svg-icons';import solar from '../assets/solar.jpg';
import panel from '../assets/panel.jpg';
import storage from '../assets/storage.jpg';
import sunpanel from '../assets/sunpanel.jpg';
import house from '../assets/house.jpg';
import generator from '../assets/generator.jpg';
import vastsolar from '../assets/vastsolar.jpg';
import '../css/greenpower.css';

function GreenPower() {
  return (
    <>
      <section className="intro-green-section">
        <div className="text-solar">
          <p className="tagline">Sustainable Energy Solutions</p>
          <h1>Powering Tomorrow with Green Energy</h1>
          <p>
            Harness the power of sustainable energy solutions with Wandall Technologies Green Power
            initiatives. Our commercial solutions are scalable to meet the needs of any size operation.
            We're committed to reducing carbon footprints while providing reliable power for your connectivity needs.
          </p>
          <p className="explore">Explore Green Solutions</p>
        </div>

        <div className="image-solar">
          <img src={solar} alt="Solar Energy" />
        </div>
      </section>

      <h1 className="section-title">Our Green Power Solutions</h1>
      <section className="three-cubes-container section">
        {[
          {
            img: panel,
            title: 'Solar Panel Solutions',
            text: 'High-efficiency solar panel installations for residential and commercial properties, designed to maximize energy production.',
          },
          {
            img: storage,
            title: 'Energy Storage Systems',
            text: 'Advanced battery storage solutions to store excess energy generated by your solar system for use during peak demand or outages.',
          },
          {
            img: sunpanel,
            title: 'Green Energy Consultation',
            text: 'Expert consultation services to help you identify the most effective green energy solutions for your specific needs and environment.',
          },
        ].map((item, idx) => (
          <div className="three-cube" key={idx}>
            <img src={item.img} alt={item.title} />
            <h2>{item.title}</h2>
            <p>{item.text}</p>
            <p className='p'>Learn more</p>
          </div>
        ))}
      </section>

      <section className="battery section">
        <div className="battery-image">
          <img src={house} alt="Battery" />
        </div>

        <div className="battery-text">
          <h1>Reliable Power for Uninterrupted Connectivity</h1>
          <p>
            Our green power solutions ensure continuous connectivity even in areas with unreliable grid power.
            Perfect for remote locations, emergencies, or reducing your dependence on conventional energy sources.
          </p>
          <ul className='custom-icon-list'>
            <li><FontAwesomeIcon icon={faCheckCircle} className="tick-icon" />Backup power for WiFi and network infrastructure</li>
            <li><FontAwesomeIcon icon={faCheckCircle} className="tick-icon" />Off-grid solutions for remote locations</li>
            <li><FontAwesomeIcon icon={faCheckCircle} className="tick-icon" />Reduced electricity costs through solar power</li>
            <li><FontAwesomeIcon icon={faCheckCircle} className="tick-icon" />Lower carbon footprint and environmental impact</li>
            <li><FontAwesomeIcon icon={faCheckCircle} className="tick-icon" />Smart energy management systems</li>
          </ul>
          <p className="explore">Request an Energy Assessment</p>
        </div>
      </section>

      <section className="things section">
        {[ 
          {
            img: generator,
            title: 'Backup Generators',
            text: 'Backup generators are essential pieces of equipment for ensuring uninterrupted power supply...',
            list: ['Portable Generators', 'Standby Generators', 'Industrial Generators']
          },
          {
            img: vastsolar,
            title: 'Commercial Solar Installation',
            text: 'There are many different types of solar power systems available...',
            list: ['Grid-tied solar power systems', 'Off-grid solar power system', 'Hybrid solar power systems']
          }
        ].map((item, idx) => (
          <div className="generator" key={idx}>
            <img src={item.img} alt={item.title} />
            <h2>{item.title}</h2>
            <p>{item.text}</p>
            <ul className='custom-icon-list' >
              {item.list.map((li, i) => <li key={i}><FontAwesomeIcon icon={faCheckCircle} className="tick-icon" />{li}</li>)}
            </ul>
            <p className="explore">Explore this Solution</p>
          </div>
        ))}
      </section>
    </>
  );
}

export default GreenPower;
